# Generated by Django 3.2.7 on 2021-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationId', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('DoB', models.DateField()),
                ('Aadhar', models.CharField(max_length=16)),
                ('department', models.CharField(default='select', max_length=30)),
                ('specialization', models.CharField(default='choose', max_length=30)),
                ('Passport', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('reservation_category', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('OC', 'OC')], max_length=20)),
                ('pwd_category', models.TextField(blank=True, max_length=255, null=True)),
                ('documents', models.FileField(upload_to='documents')),
                ('passport_pic', models.ImageField(upload_to='passport_pic')),
                ('Notes', models.TextField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('registration_no', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
