# Generated by Django 3.2.7 on 2021-09-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(default='select', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='specialization',
            field=models.CharField(default='choose', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='DoB',
            field=models.DateField(),
        ),
    ]
